dataset: 'coin'
step_number: 1

image_size: 384

#re_train_file: '/nfs4-p1/ljt/Code/BRE/coin_preprocessing/Json_for_dataset/train.json'
#re_val_file: '/nfs4-p1/ljt/Code/BRE/coin_preprocessing/Json_for_dataset/test.json'
#re_test_file: '/nfs4-p1/ljt/Code/BRE/coin_preprocessing/Json_for_dataset/test.json'

re_train_file: '/nfs4-p1/ljt/github/coin_preprocessing_new/Json_for_dataset_final/Single_Image/one_train.json'
re_val_file: '/nfs4-p1/ljt/github/coin_preprocessing_new/Json_for_dataset_final/Single_Image/one_val.json'
re_test_file: '/nfs4-p1/ljt/github/coin_preprocessing_new/Json_for_dataset_final/Single_Image/one_test.json'

batch_size_train: 4
batch_size_test: 4
batch_size_val: 4

med_config: 'configs/med_config.json'
pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base.pth'

# optimizer
weight_decay: 0.05
init_lr: 1e-5
min_lr: 0
max_epoch: 20